name: Build and/or Release

on: push

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Update apt
        run: sudo apt-get -y update

      - name: Install sdcc
        run: sudo apt-get install -y sdcc

      - name: Run make bin
        run: make bin

      - name: Run make hex
        run: make hex

      - name: Store Hex artifacts
        uses: actions/upload-artifact@v4
        with:
          name: touchkey-firmware-hex
          path: |
            touch.hex

      - name: Store Bin artifacts
        uses: actions/upload-artifact@v4
        with:
          name: touchkey-firmware-bin
          path: |
            touch.bin

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            touch.bin
            touch.hex